# Generated by Django 6.0.4 on 2026-05-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_companyinfo_employeecontact_faq_newsarticle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='No address', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='patronymic',
            field=models.CharField(blank=True, help_text='Middle name / Patronymic', max_length=100, null=True),
        ),
    ]
