# Generated by Django 6.0.4 on 2026-05-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_profile_address_profile_patronymic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='duration_weeks',
            field=models.PositiveSmallIntegerField(choices=[(1, 'One week'), (2, 'Two weeks'), (4, 'Four weeks')]),
        ),
    ]
